services:
  db:
    image: postgres:16-alpine
    container_name: games_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: game_tracker
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: games_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/game_tracker
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  pg_data: